package com.promptscalaspark.stackexchange.modeller.ModellerSchema

object PostsModellerSchema {

  case class PostHistoryModelData(
      id: Long,
      postId: Long,
      acceptedAnswerId: Long,
      answerCount: Long,
      body: String,
      closedDate: String,
      commentCount: Long,
      communityOwnedDate: String,
      favoriteCount: Long,
      lastActivityDate: String,
      lastEditDate: String,
      lastEditorDisplayName: String,
      lastEditorUserId: Long,
      ownerDisplayName: String,
      ownerUserId: Long,
      parentId: Long,
      postTypeId: Long,
      score: Long,
      tags: String,
      title: String,
      viewCount: Long,
      postHistoryTypeId: Long,
      revisionGUID: String,
      userId: Long,
      userDisplayName: String,
      comment: Option[String],
      text: String,
      closeReasonId: Option[String],
      creationDate: String
  )

  case class PostLinksModelData(
      id: Long,
      linkTypeId: Long,
      postId: Long,
      relatedPostId: Long,
      acceptedAnswerId: Long,
      answerCount: Long,
      body: String,
      closedDate: String,
      commentCount: Long,
      communityOwnedDate: String,
      creationDate: String,
      favoriteCount: Long,
      lastActivityDate: String,
      lastEditDate: String,
      lastEditorDisplayName: String,
      lastEditorUserId: Long,
      ownerDisplayName: String,
      ownerUserId: Long,
      parentId: Long,
      postTypeId: Long,
      score: Long,
      tags: String,
      title: String,
      viewCount: Long
  )

  case class PostCommentsModelData(
      id: Long,
      userId: Long,
      userDisplayName: String,
      postId: Long,
      text: String,
      commentScore: Long,
      acceptedAnswerId: Long,
      answerCount: Long,
      body: String,
      closedDate: String,
      commentCount: Long,
      communityOwnedDate: String,
      creationDate: String,
      favoriteCount: Long,
      lastActivityDate: String,
      lastEditDate: String,
      lastEditorDisplayName: String,
      lastEditorUserId: Long,
      ownerDisplayName: String,
      ownerUserId: Long,
      parentId: Long,
      postTypeId: Long,
      score: Long,
      tags: String,
      title: String,
      value: String,
      viewCount: Long
  )

  case class PostVotesModelData(
      id: Long,
      bountyAmount: Option[Long],
      postId: Long,
      pserId: Option[Long],
      voteTypeId: Long,
      acceptedAnswerId: Long,
      answerCount: Long,
      body: String,
      closedDate: String,
      commentCount: Long,
      communityOwnedDate: String,
      creationDate: String,
      favoriteCount: Long,
      lastActivityDate: String,
      lastEditDate: String,
      lastEditorDisplayName: String,
      lastEditorUserId: Long,
      ownerDisplayName: String,
      ownerUserId: Long,
      parentId: Long,
      postTypeId: Long,
      score: Long,
      tags: String,
      title: String,
      viewCount: Long
  )

}
