package modeller

object modellerSchema {


case class PostHistoryModelData(
                            Id:Long,
                            PostId: Long,
                            AcceptedAnswerId: Long ,
                            AnswerCount: Long ,
                            Body: String ,
                            ClosedDate: String ,
                            CommentCount: Long ,
                            CommunityOwnedDate: String ,
                            FavoriteCount: Long ,
                            LastActivityDate: String ,
                            LastEditDate: String ,
                            LastEditorDisplayName: String ,
                            LastEditorUserId: Long ,
                            OwnerDisplayName: String ,
                            OwnerUserId: Long ,
                            ParentId: Long ,
                            PostTypeId: Long ,
                            Score: Long ,
                            Tags: String ,
                            Title: String ,
                            ViewCount: Long,
                            PostHistoryTypeId: Long,
                            RevisionGUID: String,
                            UserId: Long,
                            UserDisplayName: String,
                            Comment: Option[String],
                            Text: String,
                            CloseReasonId: Option[String],
                            CreationDate: String
                          )


case class PostlinksModeller(
                              Id:Long,
                              LinkTypeId: Long,
                              PostId: Long,
                              RelatedPostId: Long,
                              AcceptedAnswerId: Long ,
                              AnswerCount: Long ,
                              Body: String ,
                              ClosedDate: String ,
                              CommentCount: Long ,
                              CommunityOwnedDate: String ,
                              CreationDate: String ,
                              FavoriteCount: Long ,
                              LastActivityDate: String ,
                              LastEditDate: String ,
                              LastEditorDisplayName: String ,
                              LastEditorUserId: Long ,
                              OwnerDisplayName: String ,
                              OwnerUserId: Long ,
                              ParentId: Long ,
                              PostTypeId: Long ,
                              Score: Long ,
                              Tags: String ,
                              Title: String ,
                              VALUE: String ,
                              ViewCount: Long
                            )

  case class PostCommentsModelData(
                                    UserId: Long,
                                    UserDisplayName: String,
                                    PostId: Long,
                                    Text: String,
                                    CommentsScore: Long,
                                    CommentsCreationDate: String,
                                    AcceptedAnswerId: Long ,
                                    AnswerCount: Long ,
                                    Body: String ,
                                    ClosedDate: String ,
                                    CommentCount: Long ,
                                    CommunityOwnedDate: String ,
                                    CreationDate: String ,
                                    FavoriteCount: Long ,
                                    LastActivityDate: String ,
                                    LastEditDate: String ,
                                    LastEditorDisplayName: String ,
                                    LastEditorUserId: Long ,
                                    OwnerDisplayName: String ,
                                    OwnerUserId: Long ,
                                    ParentId: Long ,
                                    PostTypeId: Long ,
                                    Score: Long ,
                                    Tags: String ,
                                    Title: String ,
                                    VALUE: String ,
                                    ViewCount: Long
                                  )

  case class PostVotesModelData(
                                 Id:Long,
                                 BountyAmount: Option[Long],
                                 PostId: Long,
                                 UserId: Option[Long],
                                 VoteTypeId: Long,
                                 AcceptedAnswerId: Long ,
                                 AnswerCount: Long ,
                                 Body: String ,
                                 ClosedDate: String ,
                                 CommentCount: Long ,
                                 CommunityOwnedDate: String ,
                                 CreationDate: String ,
                                 FavoriteCount: Long ,
                                 LastActivityDate: String ,
                                 LastEditDate: String ,
                                 LastEditorDisplayName: String ,
                                 LastEditorUserId: Long ,
                                 OwnerDisplayName: String ,
                                 OwnerUserId: Long ,
                                 ParentId: Long ,
                                 PostTypeId: Long ,
                                 Score: Long ,
                                 Tags: String ,
                                 Title: String ,
                                 ViewCount: Long
                               )

}
